"""
Data models for agent system
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class AgentType(str, Enum):
    """Agent type enumeration"""

    PLANNER = "PLANNER"
    DISPATCHER = "DISPATCHER"
    ANALYST = "ANALYST"


class Priority(str, Enum):
    """Priority level enumeration"""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ActionPlan(BaseModel):
    """Action plan generated by Planner Agent"""

    situation_summary: str = Field(
        ..., description="Brief description of the situation"
    )
    risk_assessment: str = Field(
        ..., description="Evaluation of risks and potential escalation"
    )
    recommended_actions: List[str] = Field(
        ..., description="List of specific actions to take"
    )
    resource_requirements: Dict[str, Any] = Field(
        ..., description="Estimated resources needed"
    )
    timeline: str = Field(..., description="Suggested timeline for actions")
    priority: Priority = Field(..., description="Overall priority level")


class UnitAssignment(BaseModel):
    """Unit assignment for work order"""

    unit_id: str = Field(..., description="ID of assigned unit")
    unit_type: str = Field(
        ..., description="Type of unit (maintenance, emergency, etc.)"
    )
    estimated_arrival: int = Field(..., description="Estimated arrival time in minutes")
    distance: float = Field(..., description="Distance to incident in meters")


class WorkOrderRequest(BaseModel):
    """Work order creation request"""

    incident_id: str = Field(..., description="Related incident ID")
    title: str = Field(..., description="Work order title")
    description: str = Field(..., description="Detailed description")
    priority: Priority = Field(..., description="Priority level")
    assigned_unit_id: str = Field(..., description="Assigned unit ID")
    estimated_duration: int = Field(..., description="Estimated duration in minutes")
    location: Dict[str, Any] = Field(..., description="GeoJSON location")
    zone_id: str = Field(..., description="Zone ID")


class DispatchResult(BaseModel):
    """Result of dispatch operation"""

    assignments: List[UnitAssignment] = Field(
        ..., description="List of unit assignments"
    )
    work_orders: List[WorkOrderRequest] = Field(..., description="Created work orders")
    estimated_completion: str = Field(..., description="Timeline estimates")


class Explanation(BaseModel):
    """Explanation generated by Analyst Agent"""

    explanation: str = Field(..., description="Human-readable explanation")
    key_factors: List[str] = Field(..., description="Important factors in the decision")
    recommendations: List[str] = Field(..., description="Additional recommendations")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level")


class AgentResponse(BaseModel):
    """Generic agent response"""

    agent_type: AgentType
    success: bool
    data: Dict[str, Any]
    error: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)


class ProcessIncidentRequest(BaseModel):
    """Request to process an incident"""

    incident_id: str = Field(..., description="Incident UUID")
    force_reprocess: bool = Field(
        default=False, description="Force reprocessing even if already processed"
    )


class AgentLogEntry(BaseModel):
    """Agent log entry"""

    id: int
    agent_type: str
    step: str
    data: Dict[str, Any]
    incident_id: Optional[str]
    work_order_id: Optional[str]
    timestamp: datetime
